### ISSUE TITLE
Trouble Adding Events

### ISSUE THREAD

**Issue by Phillips126** [mattlewis92/angular-bootstrap-calendar#107]
I'm fairly new to AngularJS so correct me if I am doing something wrong here, but I am having trouble adding events to the calendar through a loop.

I found that when I add events to the $scope directly, it works great - example:
```
$scope.events = [
    {title: 'test', startsAt: '2015-07-15', type: 'purple'},
    {title: 'test', startsAt: '2015-07-12', type: 'purple'}
 ];
```

The trouble I am facing is when I try to loop through an array and pushing the results into the events scope like so:
```
angular.forEach($scope.data, function(value) {
    $scope.events.push({
      title: value.title, 
      startsAt: value.date, 
      type: value.type
    });
});
```

I have to $scope.$apply() afterward, but the $scope.events list is populated successfully with my array content - the problem is, the calendar is not displaying the newly added events.

Am I doing something wrong here?

**Comment by mattlewis92** [comment]
Can you share the project with me? Otherwise I'm just guessing at answers.

**Comment by Phillips126** [comment]
Hi @mattlewis92, I've setup a simple CodePen that illustrates my issue.  I'm sure I am doing some things wrong like storing data in the $rootScope (I'm a newbie), but you can see here that the calendar doesn't seem to be updating although the $scope.events  gets two additional events added to it:

http://codepen.io/anon/pen/NqMpJM?editors=101

**Comment by mattlewis92** [comment]
Sorry about the late reply, took me a while to realise what was going on. It's because ionic does weird stuff with scopes. You need to put your ng-controller on the ion-content rather than the body tag and you should be good to go. Here's your fixed codepen: http://codepen.io/anon/pen/RPyqgE

p.s. It's really cool seeing this used with ionic, if when you're done with the project and wanted to share the final CSS I'd love to add this to the main repo an an optional ionic theme!
