### ISSUE TITLE
Question: Dev server caching

### ISSUE THREAD

**Issue by jmsherry** [mattlewis92/angular-bootstrap-calendar#158]
Hi Matt,
I'm doing some work on a fork of your repo at the moment and having some problems. I made some initial changes to the templates and then did npm run build (npm start doesn't seem to watch for some reason) and although the first set of changes took, the second and subsequent ones didn't.

Do you know if somehow it caches templates??

Thanks

James

**Comment by mattlewis92** [comment]
`npm run build` only builds files to the dist folder - if you look in [index.html](https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/index.html#L226) you will see it only points to a local file which is served by webpack. Thus you shouldn't use it for dev. `npm start` should automatically watch and reload the page on changes, you should see debug in your browser console / the terminal window you're running it on. 

FYI if you're only making template changes just [use a decorator](https://github.com/mattlewis92/angular-bootstrap-calendar#custom-directive-templates) to avoid making changes to the source - the calendar is deliberately designed so that you can override and customise it to your needs without having to edit the source :smile:

**Comment by jmsherry** [comment]
Thanks Matt. :)

I'm actually trying to modify it to be a hybrid of calendar and datepicker (so an 'add' button for each cell, or maybe drag and drop from somewhere). As I said, the watch function seems really sketchy for some reason - it either takes AGES and then does it, or it doesn't seem to pick up the changes at all. I don't know why - could be something to do with my machine, maybe?! (If I find something out I'll mention)

Thanks again... :)

**Comment by mattlewis92** [comment]
It might be an issue with webpack, what OS are you running?

**Comment by jmsherry** [comment]
Mac OSx Yosemite 10.10.5

Ever since Mavericks some things have been a bit shaky... I'll have a look into it and see if anything comes up.

Thanks Matt...

**Comment by mattlewis92** [comment]
Really odd, I'm on the same setup and am using webpack successfully across several projects. The best thing I can recommend is check the terminal output as its pretty verbose.
