### ISSUE TITLE
Install Less?

### ISSUE THREAD

**Issue by bigjollygiant14** [mattlewis92/angular-bootstrap-calendar#178]
Just installed with npm and added dependency in my MEAN stack, but am getting: 

`Uncaught Error: Cannot find module "./less/calendar.less"`

Is Less a dependency of this? I'm using Stylus for CSS preprocessor.

**Comment by mattlewis92** [comment]
Are you using browserify or webpack?

**Comment by bigjollygiant14** [comment]
Webpack

**Comment by mattlewis92** [comment]
Ah it'll be because of [this](https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/package.json#L47) which references the unbuilt source files. As a temporary workaround either install the less loader or do:
`require('angular-bootstrap-calendar/dist/js/angular-bootstrap-calendar-tpls);`

I'll push out a fix shortly.

**Comment by bigjollygiant14** [comment]
Thanks for the quick response!! I'm looking forward to playing around with this calendar. Cheers!
