### ISSUE TITLE
Can I disable the day view and just use the month view?

### ISSUE THREAD

**Issue by crossdsection** [mattlewis92/angular-bootstrap-calendar#184]
I had not given any preferences to move to a particular view, but when a specific date is clicked it opens the day view of that field.

**Comment by mattlewis92** [comment]
You can disable that with [this option](https://github.com/mattlewis92/angular-bootstrap-calendar#on-drill-down-click). Something like `on-drill-down-click="false"` should do the trick.

**Comment by fqaiser** [comment]
I tried to use on-drill-down-click="false" on the calendar directive but it didn't disable the day view. Is there anything I might be missing?

**Comment by mattlewis92** [comment]
That option has been renamed to `on-view-change-click`, see the demo for an example: http://mattlewis92.github.io/angular-bootstrap-calendar/#?example=disabling-views

**Comment by fqaiser** [comment]
Wow mattlewis92 thanks .. that was Super fast and it worked too.

**Comment by mattlewis92** [comment]
No problem, happy to help :smile:

**Comment by fqaiser** [comment]
While we are at it, can I ask one more question. Is there any way to permanently disable the Slidebox. I have tried using vm.isCellOpen = false but it is not working as I thought it would. I must say your calendar is quite good. The only reason I want to disable the slider is because if I have many events the alot of screenspace is taken by the slidebox.

**Comment by mattlewis92** [comment]
Not currently, I've created new issue for it: https://github.com/mattlewis92/angular-bootstrap-calendar/issues/292
