### ISSUE TITLE
slow with many events calendar

### ISSUE THREAD

**Issue by dchi1** [mattlewis92/angular-bootstrap-calendar#231]
I'm doing a speed test with 2000 events, but to change this week, the change is delayed Some 5 seconds.
http://embed.plnkr.co/X2hpefbbboo9uHpUseC9/

**Comment by mattlewis92** [comment]
There's no real way around this unfortunately, this is primarily due to angulars dirty checking when it watches events and I've already made all the optimisations I can think of to speed things up. The best thing I can recommend is to change your UX to show filtered events as a calendar with 2000 events isn't particularly usable anyway.
