### ISSUE TITLE
Vertically align events to top

### ISSUE THREAD

**Issue by jeffreyj100** [mattlewis92/angular-bootstrap-calendar#238]
In the week view, each added event is placed on a new line giving it a staircase appearance. 
![image](https://cloud.githubusercontent.com/assets/9508258/12004072/fc1837c4-aaf8-11e5-912b-430fdc14c33b.png)
I'm trying to get each event when added, to be vertically aligned flush to the top, instead of each new event added placed on a new line. How would I go about hacking the calendar implementation to get this result?

**Comment by mattlewis92** [comment]
This isn't something that's trivial to add or hack in as it requires every event position to be pre-calculated. If you aren't using event end dates then you could use [this option](https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/src/services/calendarConfig.js#L94) which will show the times on the week view and has a cleaner UX.

Otherwise you could use a [custom template](https://github.com/mattlewis92/angular-bootstrap-calendar#custom-directive-templates) and implement it yourself.
