### ISSUE TITLE
Async events not appearing with Ionic Framework

### ISSUE THREAD

**Issue by anand1st** [mattlewis92/angular-bootstrap-calendar#266]
Hi Matt.

I've been trying to use mwl-calendar with the ionic framework. I have written an example on codepen.io to reproduce a problem I've been facing: http://codepen.io/anand1st/pen/OMvWmq

I notice that the events show on the calendar when the ng-controller is in a directive that's directly above the mwl-calendar i.e. in the example above, it's the ion-content. The moment I move the ng-controller up to ion-pane directive, the events don't show anymore.

I believe it's linked to the this issue: https://github.com/mattlewis92/angular-bootstrap-calendar/issues/107

The problem is, I don't know if it's possible for me to move the controller to directly above the mwl-calendar in the application I'm trying to build.

Might you have any ideas/suggestions on how to overcome this issue?

**Comment by mattlewis92** [comment]
This is more of an ionic issue rather than specifically with this calendar. You should treat `ion-content` as the root element of the page, anything you do outside of it will effectively be ignored (apart from using ionic directives that are designed to be used outside of it such as `ion-nav-title` etc). I'd recommend using the ui-router to instantiate your controller rather than using `ng-controller` directly which is considered bad practice (i.e. there is no such thing as `ng-controller` in angular 2).
