### ISSUE TITLE
Dynamically changing events in a modal dialog

### ISSUE THREAD

**Issue by trevorbest** [mattlewis92/angular-bootstrap-calendar#271]
I can dynamically load events by changing $scope.events in a controller but it doesn't appear to work when the calendar is in a modal dialog.

I have created a plunker here https://plnkr.co/edit/9zlEjlAIlsfMFY4bcOPT?p=preview 

The "Add new2" button should initialize it to 2 events but doesn't. If you move the calendar and buttons outside of the modal-dialog it works fine.

**Comment by mattlewis92** [comment]
This is scope issue rather than a specific issue with the calendar. When you transclude the calendar into the modal you create a child scope so the references get messed up. You can get around this by putting your variables into a parent object like so `$scope.view.events = []` or better yet use controllerAs syntax. Here's your plunker fixed: https://plnkr.co/edit/cuuN6xzunl9MwebMBXFR?p=preview

Hope this helps :smile:
