### ISSUE TITLE
After succesfull download and clicking on html doesn't display any form

### ISSUE THREAD

**Issue by Nagendrababu88** [mattlewis92/angular-bootstrap-calendar#383]
The github issues tracker is for bug reports and feature requests _ONLY_. Please use stackoverflow or read the documentation and examples for support issues, as well as checking previous issues.

Issues that ignore this template will be closed without notice!

### Versions

Angular:

Calendar directive:

Browser name and version:

**Comment by mattlewis92** [comment]
Sorry but I don't have any idea on how to help you without a reproducible example.

**Comment by matthewtrefz** [comment]
Matt,

I have run into this issue as well, but the problem is that it is intermittent. When a screen load or refresh happens the templates do not always load (calendarConfig.templates object has no preperties).

I found that on line 94 of angular-bootstrap-calendar.js there would be times when var templates would not have any properties.

After changing angular-bootstrap-calendar.js: line 75 from if(false) to if(require) I no longer experienced the error.

At his time I am not sure how to create a plunkr to show this issue.

**Comment by mattlewis92** [comment]
You're using the wrong file, you need to be including the file with the bundled template `angular-bootstrap-calendar-tpls.js` (note the `-tpls` at the end of the file). Everything should be smooth then 😄

**Comment by matthewtrefz** [comment]
Rock On, that did it! 
Thank you for the quick reply and for porting this calendar to angular.
