### ISSUE TITLE
Clickable events from custom month template

### ISSUE THREAD

**Issue by tigrik2017** [mattlewis92/angular-bootstrap-calendar#399]
Hi. I can't make events clickable from a custom month template. Is this my mistake or something else?

```
<script id="menuMonthCell.html" type="text/ng-template">
	<div class="cal-month-day menu"
		 ng-class="{
			'cal-day-outmonth': !day.inMonth,
			'cal-day-inmonth': day.inMonth,
			'cal-day-weekend': day.isWeekend,
			'cal-day-past': day.isPast,
			'cal-day-today': day.isToday,
			'cal-day-future': day.isFuture
		}">
		<span data-cal-date ng-bind="day.label"></span>

		<div class="events-list" ng-if="day.events.length > 0">
			<a ng-if="day.isFuture" class="event">
				<i class="fa fa-pencil"></i>
			</a>
			<a ng-repeat="event in day.events track by event.id"
			   href="javascript:;"
			   ng-click="$event.stopPropagation(); vm.onEventClick({calendarEvent: event})"
			   class="event"
			   ng-class="'event-' + event.type">
				<i class="fa fa-cutlery"></i>
			</a>
		</div>

		<div class="events-list" ng-if="day.events.length == 0 && day.isFuture && !day.isWeekend">
			<a class="event hidable">
				<i class="fa fa-plus-circle"></i>
			</a>
		</div>
	</div>
</script>
```

Also tried insert my controller's function instead "vm.onEventClick". No results... It does nothing, only stops click event regression to the parents. Any suggestions?

PS: sorry for bad english...

**Comment by mattlewis92** [comment]
This is happening because the templates scope is that of the calendar and not of your controllers, so you can't access any variables from your controller in the template, only the variables in the month view controller are accessible from your custom template: https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/src/directives/mwlCalendarMonth.js

Calling `vm.onEventClick` from within the template will call the callback you pass to `on-event-click`, you can see a demo of that here: https://mattlewis92.github.io/angular-bootstrap-calendar/#?example=clickable-events (on the `markup` tab you will see the binding in action)
