### ISSUE TITLE
Random indentation of the list of events in Month view?

### ISSUE THREAD

**Issue by awwong1** [mattlewis92/angular-bootstrap-calendar#430]
### Bug description / Feature request:

When looking at the calendar in list view, some of the events are indented and some are not. Is this expected behavior?  Shouldn't all events show up left aligned? 

Here is a snapshot of what I'm seeing.

![capture](https://cloud.githubusercontent.com/assets/2760111/17907971/8f45d244-693b-11e6-9fb3-0bd23912da79.PNG)

### Link to minimally-working plunker that reproduces the issue

I can't seem to reproduce the issue. However, I've included a sample of my current codebase which utilizes the Angular Bootstrap Calendar. (Another strange thing here is that the event type doesn't change the color of the little circle next to the title)

http://plnkr.co/edit/pX4BeE0lcMMgBf3HVElk?p=preview

### Versions

Angular: ~1.5.7

Calendar directive: ^0.21.3

Browser name and version: Google Chrome, Version 52.0.2743.116 m

**Comment by mattlewis92** [comment]
If you can't reproduce it in a plunker then it's highly likely it's a CSS issue in your app that's breaking the stylings, right click > inspect element and you'll probably find it.

The event type not showing is because of breaking changes in newer versions of this module, see the [changelog](https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/CHANGELOG.md) for how to migrate (0.22.x will give you deprecation warnings in the console to help you upgrade)
