### ISSUE TITLE
Week view doesn't show multi-day / all-day events

### ISSUE THREAD

**Issue by mhenris** [mattlewis92/angular-bootstrap-calendar#450]
### Versions 0.20.2

Angular: 1.3

Calendar directive: Any

Browser name and version: All

My implementation of the calendar has some all day events, and some multi-day events.  On the day view, if an event spans that entire day, it appears as an all day event.  However, on the week view, I don't see it.

What I mean is this:  Let's say an event starts on September 20th, and ends on September 25th.

If I look at the day view for September 23rd, I see this event at the top in the section for all-day events.

However, on the week view, I will only see that event on its start day (September 20th) but no other days, even if it spans them.

**Comment by mattlewis92** [comment]
Only the day view supports the `allDay` property. For the week view it solely relies on the event `endsAt` property, so you need to make sure that's set on events for it to span multiple days. You can see this working on the [demo](https://mattlewis92.github.io/angular-bootstrap-calendar/#?example=kitchen-sink).

**Comment by mhenris** [comment]
I see that.  Let me be more specific:

In the demo, _showTimesOnWeekView_ is set to false.  In that case, each event gets its own horizontal div, regardless if it's 1 or 7 days long.  And yes, it can span multiple days.

In my scenario, there can be let's say 200 events in a week.

So every event gets its own horizontal bar.  Let's say there are 40 events on monday, and 40 events on tuesday, etc...  This shows as 40 events on monday, all stacked up, then, underneath those events, the tuesday events are present, all stacked up.  No two events can occupy the same horizontal div across all days, so the page gets very long and unmanageable.

So, in order to get around that, I had to set _showTimesOnWeekView_ to true, so that it would overlap events like it does on the day view, which makes the UI much cleaner.

However, In this case, if I was to have an event that spans the whole week, it would not be visible at all.  On the week view, that event is only visible on the day it starts, when _showTimesOnWeekView_ is set to true.

It would be cool if on the week view, there was an area at the top for events that span multiple days, when _showTimesOnWeekView_ is true

**Comment by mattlewis92** [comment]
Ah right, I didn't realise you were using the `showTimesOnWeekView` option. The issue with the normal week view you described has actually been fixed in the latest version e.g.
<img width="1047" alt="screen shot 2016-09-21 at 15 45 26" src="https://cloud.githubusercontent.com/assets/6425649/18715845/9fa7f8cc-8012-11e6-86b9-247e982bc2e4.png">

There is currently no support for the feature you described on the alternate week view, I'd happily review and accept a PR to implement it but it's not something I have the time or energy to implement myself (all my open source time is now focused on angular2 dev work). Sorry!
