### ISSUE TITLE
Resetting the events array to a deep clone doesn't re-add the id field

### ISSUE THREAD

**Issue by mattlewis92** [mattlewis92/angular-bootstrap-calendar#457]
Continued from https://github.com/mattlewis92/angular-bootstrap-calendar/pull/454#issuecomment-251872816

**Comment by dam417** [comment]
Hi, I tried setting the $id to enumerable but it didn't work. It turned out that angular.equals, which angular $watch uses to detect changes when in deep watch ignores properties that start with the dollar sign ($). Therefore, I changed property $id to watchid (I couldn't use _id since I'm already using that field in my application) and set it to enumerable and it worked. Setting to enumerable as you mentioned was required also. This also required changing $id to watchid in all the templates.

**Comment by mattlewis92** [comment]
Ah the `$` prefix makes sense, thanks for digging into that, I will get a fix out as soon as I have the time :)
