### ISSUE TITLE
How to disable interact.js dependency

### ISSUE THREAD

**Issue by STheFox** [mattlewis92/angular-bootstrap-calendar#508]
I get following errors in my console:
```
Uncaught TypeError: Cannot read property 'pageX' of undefined
    at getXY (interact.js:649)
    at getPageXY (interact.js:666)
    at setEventXY (interact.js:610)
    at Interaction.setEventXY (interact.js:1319)
    at Interaction.pointerMove (interact.js:1782)
    at HTMLDocument.realWindow.InteractEvent.target (interact.js:3348)
    getXY @ interact.js:649
    getPageXY @ interact.js:666
    setEventXY @ interact.js:610
    setEventXY @ interact.js:1319
    pointerMove @ interact.js:1782
    realWindow.InteractEvent.target @ interact.js:3348
```

How to disable interact.js to be loaded since I don't use drag-and-drop functionalities?

**Comment by mattlewis92** [comment]
This issue is actually fixed in the latest version of interact.js, but I can see your use case about not including interact.js if you're not using drag and drop. I assume you're installing from npm, you can either use `npm install --no-optional` to not install it, or use your bundler to exclude the `interactjs` module from being included. If that doesn't work for you let me know. Hope that helps! 😃
