### ISSUE TITLE
create custom build for my project

### ISSUE THREAD

**Issue by sandeshfromindia** [mattlewis92/angular-bootstrap-calendar#522]
Hi Matt.

I wanted to create new custom view to add new events in the calendar, i want to generate that new view like you generated for month , week views in your calendar, I able generate my custom view in the same way you have done in your calendar, and generated the view, also i was trying to use 'npm run build' for my custom build but its gives lots of errors while building, and my new templates , corresponding directives are not get included in the build. Need some help to create my custom build. i have uploaded some pics which will give some basic idea of what i wanted to do.
![new create_event view](https://cloud.githubusercontent.com/assets/10735371/21921208/6699472e-d98c-11e6-851c-c292d0a02bd1.jpg)
![npm build problem](https://cloud.githubusercontent.com/assets/10735371/21921209/669955c0-d98c-11e6-91ed-8daa91a89850.jpg)

**Comment by mattlewis92** [comment]
Those errors are from eslint, you should be able to configure your IDE to use unix style line endings, or just disable the rule in the eslint config. See the eslint docs for more info: http://eslint.org/docs/rules/linebreak-style

**Comment by sandeshfromindia** [comment]
ok..
actually i wanted to add extra custom view like you created for month, week over same calendar view, without changing in your core files.

**Comment by mattlewis92** [comment]
If you want a custom view I'd recommend just creating a completely separate component and then in the nav buttons link to it. It'll keep your code base a lot simpler. In the ng2 version I actually removed the parent calendar component and split everything into 3 components for day / week / month views with your exact use case in mind.

The build will be failing because of the lint errors, it's a deliberate design to maintain consistency across the code base.
