### ISSUE TITLE
Calendar not rendering the days correctly when you set a moment default timezone

### ISSUE THREAD

**Issue by CLenon** [mattlewis92/angular-bootstrap-calendar#544]
Hey guys, thanks for your approach sharing this lib with the community, is a good library. I have been having some trouble to implement and set a default timezone with moment as the date formatter.

When you set the timezone using moment, the calendar not setting the events in the correct day. I do not know why, maybe i'm doing something wrong. I will appreceate your help.

I fork to my plunks the same example project you have in your page and i include these changes:
1. Add a event with a timezone format

`vm.events = [{
    title: 'An event',
    color: calendarConfig.colorTypes.warning,
    startsAt: moment('2017-02-21T17:00:00-06:00'),
    endsAt: moment('2017-02-21T17:30:00-06:00'),
    draggable: false,
    resizable: false,
    actions: actions
  }];`

2. Add a timezone using moment class

` var tz = 'America/Phoenix' //This timezone is -7`
`moment.tz.setDefault(tz); //set default timezone`

If you can see the calendar not rendering the days correctly when you set a timezone -7, -8 -9, and ahead etc... In the following screenshot the calendar not setting the current day.

![image](https://cloud.githubusercontent.com/assets/4239218/23175426/f43fe1a8-f824-11e6-96c6-d205fc73ef08.png)

Now, if you set a timezone -6,-5,-4,-3.. 0 everything works fine.

This is the plunk link [_plunker code_](http://plnkr.co/edit/1CCUjVfDTo3om7AWcqx7?p=preview)

I will appreciate your help in what i'm doing wrong.

**Thanks.** 

**Details**
Angular: 1.6.2
Browser name and version: Chrome

**Comment by mattlewis92** [comment]
This occurs because the [underlying lib](https://github.com/mattlewis92/calendar-utils) that powers this calendar and the angular 2 version uses date-fns and not moment, thus all moment timezone stuff is ignored. I'm actually working on dropping moment as a dependency and replacing it with date-fns so it won't be possible to fix this long term. The best thing I can recommend is having your API return all days in UTC and then manually changing the timezone of them to your local time.

**Comment by wootwoot1234** [comment]
@mattlewis92 I'm coming up against this timezone issue too.  If I have the server return the dates/times in UTC can you explain how I manually would change them to the local timezone?
