### ISSUE TITLE
Using angular-dragdrop instead of interactjs

### ISSUE THREAD

**Issue by yasserht** [mattlewis92/angular-bootstrap-calendar#608]
Hello @mattlewis92 @burtek , is there a way to use [ angular-dragdrop](http://codef0rmer.github.io/angular-dragdrop) instead of interactjs to drag external events into the calendar ?  I can drag events now but when I drop them I get this error : angular.js:14525 TypeError: Cannot read property 'startsAt' of undefined. Thank you

**Comment by burtek** [comment]
Your events must have `startsAt` field set to correct value prior to drag-and-drop action. Without this you;d get same error with angular-dragdrop

**Comment by yasserht** [comment]
It's already set to a correct value, I'll provide a plunker

**Comment by burtek** [comment]
Please, do, it will help a lot.

**Comment by yasserht** [comment]
here is the plunker @burtek http://plnkr.co/edit/49YTdAhDeRhwkGownAL2?p=preview , thank you

**Comment by burtek** [comment]
You have multiple errors in your code. I.e. in line 30:
`var men = vm.men.indexOf(event);`
There is no `vm.men` in this controller. There is also no such object as `event`. Please, correct all mistakes first, incl. mess with using both `vm` and `$scope`.

**Comment by yasserht** [comment]
https://plnkr.co/edit/U1e78k79DH6pfWnx5ERH?p=preview here is an updated plunker

**Comment by burtek** [comment]
**Answer:** The problem with `ngDragDrop` is that it uses JSON to send data and so all `Date()` objects get simplified to ISO string (which is not accepted by this calendar). You may need to modify the data somewhere (I don't know where, as I'm not familiar with `ngDragDrop`.
<hr>
**NB:** Is there any particular reason you want to use `ngDragDrop` instead of `interactJS`? The latter is confirmed to work without problems with this calendar.

Also watch out for your Markup - in your code you have two parameters which may collide:

`ui-on-Drop="onDrop($event,$data,events)"
on-event-times-changed="vm.onDrop(calendarEvent, calendarNewEventStart, calendarNewEventEnd)"`

try to avoid doing that (which again can be easily achieved by using `interactJS`).

I won't be able to help you anymore as I'm not familiar with `ngDragDrop`

**Comment by yasserht** [comment]
Thank you for your answer, the problem with interactJS is that it's using jquery and my app is  fully angular, so that is causing problems, draggable: true, for example inside the controller.

**Comment by mattlewis92** [comment]
Interact has no dependency on jquery, it's fully standalone (which was why I picked it)

**Comment by yasserht** [comment]
Hello @mattlewis92 , but isn't draggable: true or resizable: true a dom manupulation, and cannot be done in a controller. I have my app deployed now and interactjs isn't loading, no idea why, that's why i decided to use a directive for drag and drop

**Comment by mattlewis92** [comment]
interact is used inside a directive though: https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/src/directives/mwlDraggable.js

If interact isn't loading in production make sure it's included before this calendar, otherwise it won't pick it up. You could try adding it via a cdn link before yours apps bundle: http://interactjs.io/docs/#

**Comment by yasserht** [comment]
I'll try that, thank you, I just realized even when I install angular-bootstrap-calendar with bower, /src/directives file is empty

**Comment by mattlewis92** [comment]
That's because only the dist files are available (all the src files are bundled into one file, otherwise you'd have trouble including them all the files in arc manually)

**Comment by yasserht** [comment]
So there is no way to use dragndrop or any other directive coz I can't modify the calendar right @mattlewis92 ?

**Comment by mattlewis92** [comment]
Nope the only option you have is the directive that's bundled. You could always fork this lib and use the other drag and drop library but I don't really see what benefit that would give you

**Comment by yasserht** [comment]
@mattlewis92 @burtek  I solved the problem by installing interact first 
`  "angular-bootstrap-calendar" : {
      "dependencies" : {
        "interactjs": "interact#^1.2.8",
        "angular": ">=1.3.0",
    		"moment": "^2.10.0",
    		"bootstrap": "^3.3.4"
      }
    }`
