### ISSUE TITLE
Help with v 0.9.2

### ISSUE THREAD

**Issue by el-besto** [mattlewis92/angular-bootstrap-calendar#83]
Hi, we are using angular 1.2.28 so I am trying to use the zipped release for 0.9.2.

Wondering if the event objecr expects event.starts_at or event.startsAt

I had been working with version 0.9.3 (I belive) but that source is now gone. Am I mistaken about there being a version 0.9.3? I think that the version I had did have startsAt, and the templates were in the src not the root. 

I can modify my logic to build events with either key, but wanted to check with you first. 

When I try to rollback the error I get is that it cannot find main.js. Is this an issue with the gulp build? Perhaps my best bet is to just reconfigure the object on my end and baseline on the functional 0.9.2 build.

Thanks for the help.

**Comment by mattlewis92** [comment]
You can still use the 0.10.x release with angular 1.2.x, I haven't yet dropped support for angular 1.2.x

You can view the docs for any previous version. For 0.9.x [see here](https://github.com/mattlewis92/angular-bootstrap-calendar/tree/0.9.2)

There was never a 0.9.3, 0.10.x has the templates in src and uses startsAt instead of starts_at

You should never be including main.js, only use the files from the dist folder.

Hope that helps :)

**Comment by el-besto** [comment]
Ok cool thanks for the quick response. I will try the build with the newer version and go from there :)
